#!/usr/bin/env python3
"""Convert the static site (site/src/*.html) into Shopify theme files (shopify/theme/).

Output:
  layout/woven.liquid           site look (fonts, header, footer) around Shopify content
  sections/wt-page.liquid       one section that renders a page snippet (home / blanket / storybook / gift-set)
  snippets/wt-<page>.liquid     page body converted from site/src/<page>.html
  snippets/wt-buy.liquid        real Shopify product form (variant chips, personalization, checkout)
  templates/index.json, templates/product.wt-<page>.json
  assets/wt-site.css            site/css/site.css + store additions
Media (img/, tex/, video/) stays on the Vercel deployment (MEDIA below).
3D bundle: shopify/theme/assets/wt-scenes.js (esbuild of site/js/scenes.js).
"""
import json, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC, OUT = ROOT / "site" / "src", ROOT / "shopify" / "theme"
MEDIA = "https://woven-tails.vercel.app/"
HANDLES = {"blanket": "custom-pet-portrait-woven-blanket", "storybook": "personalized-pet-storybook", "gift-set": "pet-portrait-gift-set"}


def body_of(page):
    html = (SRC / f"{page}.html").read_text()
    main = re.search(r"<main>(.*?)</main>", html, re.S).group(1)
    buybar = re.search(r'(<div class="buybar">.*?</a></div>)', html, re.S)
    script = re.search(r'<script type="module">(.*?)</script>', html, re.S).group(1)
    return main, (buybar.group(1) if buybar else ""), script


def rewrite(s, page):
    s = re.sub(r'(src|poster)="(img|tex|video)/', lambda m: f'{m.group(1)}="{MEDIA}{m.group(2)}/', s)
    for p, h in HANDLES.items():
        own = (p == page)
        s = s.replace(f'href="https://shop.woventails.com/products/{h}"', 'href="#create"' if own else f'href="/products/{h}"')
        s = s.replace(f'href="/{p}#create"', 'href="#create"' if own else f'href="/products/{h}#create"')
        s = s.replace(f'href="/{p}"', 'href="#create"' if own else f'href="/products/{h}"')
    s = s.replace('href="https://shop.woventails.com/', 'href="/')
    return s


def page_script(script):
    script = script.replace('from "./js/scenes.js"', f'from "{MEDIA}theme-assets/wt-scenes.js"')
    script = re.sub(r'(init(?:Blanket|Book|Gift)\([^,]+,\s*\{)', lambda m: m.group(1) + f' base: "{MEDIA}tex/",', script)
    return script


def convert(page):
    main, buybar, script = body_of(page)
    main = rewrite(main, page)
    buybar = rewrite(buybar, page)
    script = page_script(script)
    if page in HANDLES:
        # hero buy area -> real product form
        main = re.sub(r'<div class="cta-row" data-buy-anchor>.*?</div>', "{% render 'wt-buy', product: product %}", main, count=1, flags=re.S)
        main = main.replace('<section class="wrap hero">', '<section class="wrap hero" id="create">')
        # the art-style chips are replaced by the variant chips in the form
        main = re.sub(r'\s*<div class="picker">\s*<span class="picker-label">Art style</span>.*?</div>\s*</div>', "", main, count=1, flags=re.S)
        main = main.replace("After checkout we email you to send your pet's photo", "Upload your pet's photo above, or email it after checkout")
        main = main.replace("Add it in the order note and we'll place it under the portrait.", "Type it in the name box above and we'll weave it under the portrait.")
        main = main.replace("Reply to our email with 1–3 clear photos of your pet's face. Phone photos are perfect.", "Upload a clear photo of your pet's face, or reply to our email with it. Phone photos are perfect.")
        script = script.replace('document.getElementById("styles").addEventListener("pick", (e) => { state.style = e.detail; apply(); });',
            'document.addEventListener("wt:style", (e) => { state.style = e.detail; if (!state.user) apply(); });\n    document.addEventListener("wt:art", (e) => { state.user = true; b.setArtURL(e.detail); });\n    document.getElementById("pets").addEventListener("pick", () => { state.user = false; });')
        script = script.replace('initGift(document.getElementById("gift-stage"),', 'const g = initGift(document.getElementById("gift-stage"),')
    head = "{%- comment -%} Generated by scripts/build_shopify_theme.py from site/src/" + page + ".html. Edit the source, then re-run. {%- endcomment -%}\n"
    return head + "<main>" + main + "</main>\n" + buybar + '\n<script type="module">' + script + "</script>\n"


LAYOUT = """<!doctype html>
<html lang="{{ request.locale.iso_code }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>{{ page_title }}{% unless page_title contains shop.name %} · {{ shop.name }}{% endunless %}</title>
{%- if page_description %}<meta name="description" content="{{ page_description | escape }}">{% endif %}
<link rel="canonical" href="{{ canonical_url }}">
{%- liquid
  assign og_image = '__MEDIA__img/og-home.jpg'
  if product
    case product.handle
      when 'custom-pet-portrait-woven-blanket'
        assign og_image = '__MEDIA__img/og-blanket.jpg'
      when 'personalized-pet-storybook'
        assign og_image = '__MEDIA__img/og-storybook.jpg'
      when 'pet-portrait-gift-set'
        assign og_image = '__MEDIA__img/og-gift-set.jpg'
    endcase
  endif
-%}
<meta property="og:site_name" content="{{ shop.name }}">
<meta property="og:title" content="{{ page_title | escape }}">
<meta property="og:description" content="{{ page_description | escape }}">
<meta property="og:url" content="{{ canonical_url }}">
<meta property="og:image" content="{{ og_image }}">
<meta property="og:type" content="{% if product %}product{% else %}website{% endif %}">
<meta name="twitter:card" content="summary_large_image">
{%- if settings.favicon != blank %}<link rel="icon" href="{{ settings.favicon | image_url: width: 64 }}">{% endif %}
<link rel="apple-touch-icon" href="__MEDIA__img/apple-touch-icon.png">
<meta name="theme-color" content="#1F3127">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,400..700,0..100,0..1;1,9..144,400..700,0..100,0..1&family=Nunito:wght@400;600;700;800&display=swap">
<link rel="stylesheet" href="__MEDIA__theme-assets/wt-site.css">
<script>document.documentElement.classList.add("js")</script>
{{ content_for_header }}
</head>
<body data-page="{% if product %}{{ product.handle }}{% else %}{{ template.name }}{% endif %}">
<a class="skip" href="#main">Skip to content</a>
<div class="announce">Order by Dec 10 for Christmas · Free US shipping<span class="hide-sm"> · You approve the art first</span></div>
<header class="site-head">
  <div class="wrap">
    <a class="brand" href="/" aria-label="Woven Tails home">
      <svg viewBox="0 0 40 40" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round"><ellipse cx="11" cy="13" rx="4" ry="5.5"/><ellipse cx="20" cy="9" rx="4" ry="5.5"/><ellipse cx="29" cy="13" rx="4" ry="5.5"/><path d="M12 29c0-6 4-10 8-10s8 4 8 10c0 4-4 6-8 6s-8-2-8-6z"/><path d="M15 27c3 2 7 2 10 0M15 31c3-2 7-2 10 0" stroke-width="1.8"/></g></svg>
      Woven Tails
    </a>
    <nav class="nav" aria-label="Main">
      <a href="/products/custom-pet-portrait-woven-blanket" data-nav="custom-pet-portrait-woven-blanket">Woven blanket</a>
      <a href="/products/personalized-pet-storybook" data-nav="personalized-pet-storybook">Storybook</a>
      <a href="/products/pet-portrait-gift-set" data-nav="pet-portrait-gift-set" class="hide-sm">Gift set</a>
      {%- if cart.item_count > 0 -%}<a href="/cart" class="cart-link" aria-label="Cart, {{ cart.item_count }} items">Cart ({{ cart.item_count }})</a>{%- endif -%}
      <a class="btn small" href="{% if product %}#create{% else %}/products/custom-pet-portrait-woven-blanket#create{% endif %}">Create yours</a>
    </nav>
  </div>
</header>
<div id="main">{{ content_for_layout }}</div>
<footer class="site-foot">
  <div class="wrap">
    <div class="stack">
      <a class="brand" href="/">Woven Tails</a>
      <p class="muted">Your pet, illustrated from your photo, woven into cotton or starring in their own book. Made to order in the USA.</p>
      <p class="disclose">Artwork is AI-assisted and checked by hand; you approve every design before it's made. Lifestyle images on this site are illustrations of the products.</p>
    </div>
    <div><h4>Shop</h4><ul><li><a href="/products/custom-pet-portrait-woven-blanket">Woven blanket · $64</a></li><li><a href="/products/personalized-pet-storybook">Storybook · $42</a></li><li><a href="/products/pet-portrait-gift-set">Gift set · $99</a></li></ul></div>
    <div><h4>Help</h4><ul><li><a href="/pages/send-your-photo">Send your pet's photo</a></li><li><a href="/policies/shipping-policy">Shipping</a></li><li><a href="/policies/refund-policy">Returns &amp; replacements</a></li><li><a href="/pages/faq">FAQ</a></li><li><a href="/pages/contact">Contact</a></li><li><a href="mailto:hello@woventails.com">hello@woventails.com</a></li></ul></div>
    <div><h4>Legal</h4><ul><li><a href="/policies/privacy-policy">Privacy</a></li><li><a href="/policies/terms-of-service">Terms</a></li><li><a href="/pages/data-sharing-opt-out">Your privacy choices</a></li></ul></div>
  </div>
</footer>
<script src="__MEDIA__theme-assets/wt-site.js" defer></script>
</body>
</html>
""".replace("__MEDIA__", MEDIA)

BUY = """{%- comment -%} Woven Tails buy form: variant chips + personalization, straight to checkout. {%- endcomment -%}
{%- assign current = product.selected_or_first_available_variant -%}
<div class="wt-buy" data-buy-anchor>
  {%- form 'product', product, id: 'wt-buy-form', class: 'wt-buy__form' -%}
    <input type="hidden" name="id" value="{{ current.id }}" data-wt-variant>
    <input type="hidden" name="return_to" value="/checkout">
    {%- unless product.has_only_default_variant -%}
      {%- for option in product.options_with_values -%}
        <div class="picker">
          <span class="picker-label">{{ option.name }}</span>
          <div class="chips">
            {%- for value in option.values -%}
              <label class="chip text"><input class="wt-opt" type="radio" name="wt-option-{{ forloop.parentloop.index0 }}" data-index="{{ forloop.parentloop.index0 }}" value="{{ value | escape }}" {% if option.selected_value == value %}checked{% endif %}><span>{{ value }}</span></label>
            {%- endfor -%}
          </div>
        </div>
      {%- endfor -%}
    {%- endunless -%}
    {% render 'woven-personalization', product: product, uid: 'buy' %}
    <button type="submit" class="btn wt-buy__btn" {% unless current.available %}disabled{% endunless %}>Create mine · <span data-wt-price>{{ current.price | money_without_trailing_zeros }}</span></button>
    <p class="note wt-buy__note">Secure checkout · free US shipping · you approve the art before anything is made</p>
  {%- endform -%}
  <script type="application/json" data-wt-variants>[{%- for v in product.variants -%}{"id":{{ v.id }},"options":{{ v.options | json }},"price":{{ v.price | money_without_trailing_zeros | json }},"available":{{ v.available | json }}}{% unless forloop.last %},{% endunless %}{%- endfor -%}]</script>
  <script>
    (() => {
      const root = document.currentScript.closest('.wt-buy');
      const variants = JSON.parse(root.querySelector('[data-wt-variants]').textContent);
      const idInput = root.querySelector('[data-wt-variant]'), price = root.querySelector('[data-wt-price]'), btn = root.querySelector('.wt-buy__btn');
      const STYLE = [[/royal/i, 'royal'], [/christmas|scarf/i, 'christmas'], [/pop/i, 'pop']];
      const sync = () => {
        const sel = [...root.querySelectorAll('.wt-opt:checked')].sort((a, b) => a.dataset.index - b.dataset.index).map((i) => i.value);
        const v = variants.find((x) => x.options.every((o, i) => o === sel[i]));
        if (v) { idInput.value = v.id; price.textContent = v.price; btn.disabled = !v.available; }
        for (const val of sel) for (const [re, st] of STYLE) if (re.test(val)) document.dispatchEvent(new CustomEvent('wt:style', { detail: st }));
      };
      root.addEventListener('change', (e) => { if (e.target.classList.contains('wt-opt')) sync(); });
      root.querySelector('form').addEventListener('submit', () => { btn.disabled = true; btn.textContent = 'Taking you to checkout…'; });
    })();
  </script>
</div>
"""

SECTION = """{%- liquid
  assign page = section.settings.page
-%}
{%- case page -%}
  {%- when 'home' -%}{% render 'wt-home' %}
  {%- when 'blanket' -%}{% render 'wt-blanket', product: product %}
  {%- when 'storybook' -%}{% render 'wt-storybook', product: product %}
  {%- when 'gift-set' -%}{% render 'wt-gift-set', product: product %}
{%- endcase -%}
{% schema %}
{
  "name": "Woven Tails page",
  "settings": [
    { "type": "select", "id": "page", "label": "Page", "default": "home",
      "options": [ { "value": "home", "label": "Home" }, { "value": "blanket", "label": "Blanket" }, { "value": "storybook", "label": "Storybook" }, { "value": "gift-set", "label": "Gift set" } ] }
  ],
  "presets": [ { "name": "Woven Tails page" } ]
}
{% endschema %}
"""

EXTRA_CSS = """
/* ---- Shopify store additions ---- */
.skip { position: absolute; left: -9999px; }
.skip:focus { left: 16px; top: 16px; z-index: 99; background: var(--raised); padding: 8px 12px; border-radius: 8px; }
.cart-link { font-weight: 800; }
.wt-buy__form { display: grid; gap: 1.1rem; }
.wt-buy .chip { position: relative; }
.wt-buy .chip input { position: absolute; inset: 0; opacity: 0; cursor: pointer; margin: 0; }
.wt-buy .chip:has(input:checked) { border-color: var(--thread); box-shadow: inset 0 0 0 1.5px var(--thread); }
.wt-buy .chip:has(input:focus-visible) { outline: 3px solid var(--thread); outline-offset: 3px; }
.wt-buy__btn { width: 100%; font-size: var(--step-0); }
.wt-buy__btn[disabled] { opacity: .6; cursor: progress; }
.wt-buy__note { text-align: center; }
.wt-buy .wt-personalize { margin: 0; background: var(--raised); border-color: var(--line); }
"""


def main():
    (OUT / "layout").mkdir(parents=True, exist_ok=True)
    for d in ("sections", "snippets", "templates", "assets"):
        (OUT / d).mkdir(parents=True, exist_ok=True)
    (OUT / "layout" / "woven.liquid").write_text(LAYOUT)
    (OUT / "sections" / "wt-page.liquid").write_text(SECTION)
    (OUT / "snippets" / "wt-buy.liquid").write_text(BUY)
    for page in ("index", "blanket", "storybook", "gift-set"):
        name = "home" if page == "index" else page
        (OUT / "snippets" / f"wt-{name}.liquid").write_text(convert(page))
    (OUT / "templates" / "index.json").write_text(json.dumps(
        {"layout": "woven", "sections": {"main": {"type": "wt-page", "settings": {"page": "home"}}}, "order": ["main"]}, indent=2))
    for page in HANDLES:
        (OUT / "templates" / f"product.wt-{page}.json").write_text(json.dumps(
            {"layout": "woven", "sections": {"main": {"type": "wt-page", "settings": {"page": page}}}, "order": ["main"]}, indent=2))
    (OUT / "assets" / "wt-site.css").write_text((ROOT / "site" / "css" / "site.css").read_text() + EXTRA_CSS)
    (OUT / "assets" / "wt-site.js").write_text((ROOT / "site" / "js" / "site.js").read_text())
    # mirror theme JS/CSS to the Vercel site so they can be updated without republishing the theme
    pub = ROOT / "site" / "theme-assets"; pub.mkdir(exist_ok=True)
    for f in ("wt-site.css", "wt-site.js", "wt-scenes.js", "wt-stylize.js"):
        (pub / f).write_bytes((OUT / "assets" / f).read_bytes())
    print("theme files written to", OUT)


if __name__ == "__main__":
    main()
